/** 고객 프로필 이름 길이 제한 */
export const CUSTOMER_PROFILE_NAME_MAX_LENGTH = 50;

/** 기사 프로필 입력값 길이/범위 제한 */
export const MOVER_PROFILE_NICKNAME_MIN_LENGTH = 2;
export const MOVER_PROFILE_NICKNAME_MAX_LENGTH = 20;

export const MOVER_PROFILE_CAREER_MIN = 0;
export const MOVER_PROFILE_CAREER_MAX = 100;

export const MOVER_PROFILE_SHORT_INTRO_MAX_LENGTH = 100;
export const MOVER_PROFILE_DESCRIPTION_MAX_LENGTH = 1000;
