import type { Mover, MoverSort } from "@/types/mover";

export const SORT_OPTIONS: { value: MoverSort; label: string }[] = [
  { value: "reviewCount", label: "리뷰 많은순" },
  { value: "rating", label: "평점 높은순" },
  { value: "career", label: "경력 높은순" },
  { value: "confirmedCount", label: "확정 많은순" },
];

const DEFAULT_PROFILE = "/images/profile-character.png";

/* NOTE: API 연동 전 MOCK 데이터 */
export const MOCK_MOVERS: Mover[] = [
  {
    id: "1",
    name: "김서울",
    serviceType: "SMALL",
    serviceAreas: [1, 9], // 서울, 경기
    title: "서울·경기 소형이사 안전 운송",
    description: "소형이사 전문. 안전 포장과 당일 견적을 제공합니다.",
    rating: 4.9,
    reviewCount: 210,
    careerYears: 8,
    confirmedCount: 180,
    favoriteCount: 95,
    isFavorite: false,
    profileImageSrc: DEFAULT_PROFILE,
  },
  {
    id: "2",
    name: "박부산",
    serviceType: "SMALL",
    serviceAreas: [2, 16], // 부산, 경남
    title: "부산 소형이사 빠른 안전 이동",
    description: "부산·경남 중심의 소형이사. 안전한 운반을 약속드립니다.",
    rating: 4.2,
    reviewCount: 95,
    careerYears: 5,
    confirmedCount: 410,
    favoriteCount: 40,
    isFavorite: true,
    profileImageSrc: DEFAULT_PROFILE,
  },
  {
    id: "3",
    name: "이가경",
    serviceType: "OFFICE",
    serviceAreas: [1, 4], // 서울, 인천
    title: "사무실 이전 전문 컨설팅",
    description: "사무실·상가 이전 경력 15년. 야간 작업 가능합니다.",
    rating: 4.6,
    reviewCount: 140,
    careerYears: 15,
    confirmedCount: 220,
    favoriteCount: 120,
    isFavorite: true,
    profileImageSrc: DEFAULT_PROFILE,
  },
  {
    id: "4",
    name: "최가정",
    serviceType: "HOME",
    serviceAreas: [1], // 서울
    title: "가정이사 짐 케어 서비스",
    description: "가정이사 짐 분류부터 배치까지 꼼꼼히 도와드립니다.",
    rating: 4.4,
    reviewCount: 60,
    careerYears: 4,
    confirmedCount: 75,
    favoriteCount: 22,
    isFavorite: false,
    profileImageSrc: DEFAULT_PROFILE,
  },
  {
    id: "5",
    name: "한경기",
    serviceType: "HOME",
    serviceAreas: [9, 4], // 경기, 인천
    title: "경기·인천 가정이사",
    description: "가정이사 리뷰가 많은 경기권 전문 기사입니다.",
    rating: 4.7,
    reviewCount: 320,
    careerYears: 12,
    confirmedCount: 290,
    favoriteCount: 200,
    isFavorite: true,
    profileImageSrc: DEFAULT_PROFILE,
  },
  {
    id: "6",
    name: "강도시",
    serviceType: "OFFICE",
    serviceAreas: [2, 7], // 부산, 울산
    title: "동남권 사무실 이사",
    description: "부산·울산 사무실 이사. 장비 이전 경험 풍부합니다.",
    rating: 3.9,
    reviewCount: 45,
    careerYears: 6,
    confirmedCount: 130,
    favoriteCount: 18,
    isFavorite: false,
    profileImageSrc: DEFAULT_PROFILE,
  },
  {
    id: "7",
    name: "오제주",
    serviceType: "OFFICE",
    serviceAreas: [17], // 제주
    title: "제주 사무실·상가 이전",
    description: "제주 지역 사무실 이전 특화. 평점 최상위입니다.",
    rating: 5.0,
    reviewCount: 88,
    careerYears: 9,
    confirmedCount: 95,
    favoriteCount: 70,
    isFavorite: true,
    profileImageSrc: DEFAULT_PROFILE,
  },
  {
    id: "8",
    name: "정이사",
    serviceType: "SMALL",
    serviceAreas: [6, 12], // 대전, 충남
    title: "대전·충남 소형이사",
    description: "충청권 소형이사. 원룸·투룸 중심으로 진행합니다.",
    rating: 4.1,
    reviewCount: 30,
    careerYears: 3,
    confirmedCount: 55,
    favoriteCount: 12,
    isFavorite: false,
    profileImageSrc: DEFAULT_PROFILE,
  },
];

/** NOTE: 찜한 기사님 사이드바용 MOCK. 찜 목록 API 연동 전 */
export const MOCK_FAVORITE_MOVERS: Mover[] = [
  {
    id: "f1",
    name: "한경기",
    serviceType: "HOME",
    serviceAreas: [9, 4],
    title: "경기·인천 가정이사",
    description: "가정이사 리뷰가 많은 경기권 전문 기사입니다.",
    rating: 4.7,
    reviewCount: 320,
    careerYears: 12,
    confirmedCount: 290,
    favoriteCount: 200,
    isFavorite: true,
    profileImageSrc: DEFAULT_PROFILE,
  },
  {
    id: "f2",
    name: "이가경",
    serviceType: "OFFICE",
    serviceAreas: [1, 4],
    title: "사무실 이전 전문 컨설팅",
    description: "사무실·상가 이전 경력 15년. 야간 작업 가능합니다.",
    rating: 4.6,
    reviewCount: 140,
    careerYears: 15,
    confirmedCount: 220,
    favoriteCount: 120,
    isFavorite: true,
    profileImageSrc: DEFAULT_PROFILE,
  },
  {
    id: "f3",
    name: "오제주",
    serviceType: "OFFICE",
    serviceAreas: [17],
    title: "제주 사무실·상가 이전",
    description: "제주 지역 사무실 이전 특화. 평점 최상위입니다.",
    rating: 5.0,
    reviewCount: 88,
    careerYears: 9,
    confirmedCount: 95,
    favoriteCount: 70,
    isFavorite: true,
    profileImageSrc: DEFAULT_PROFILE,
  },
];
